# Generated by Django 4.1.3 on 2022-11-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Limpieza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cepillos',
            new_name='Cepillo',
        ),
        migrations.RenameModel(
            old_name='descartables',
            new_name='Descartable',
        ),
        migrations.RenameModel(
            old_name='quimicos',
            new_name='Quimico',
        ),
    ]
